### ISSUE TITLE
they seem to be running from eachother

### ISSUE THREAD

**Issue by mellomlia** [AqwamCreates/Roblox-Source-Codes#3]
they just seem to run after eachother in circles, ai 1 is running away from ai 2 but ai 2 is chasing it, it seems like they only learn to chase eachother when they arent facing eachother

**Comment by AqwamCreates** [comment]
Can we not misuse the "Issues" section for non bug-related stuff? Otherwise, I will start blocking you from interacting from accessing the repository so that the other user's aren't flooded with non-useful information. Put this on DevForum thread instead so that you can discuss this problem with other people.
